apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  labels:
    type: local
spec:
  storageClassName: data
  capacity:
    storage: 50Gi
  accessModes: ["ReadWriteOnce"]
  hostPath:
    path: /data
    type: DirectoryOrCreate