apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-datasets
  labels:
    type: local
spec:
  storageClassName: datasets
  capacity:
    storage: 50Gi
  accessModes: ["ReadWriteOnce"]
  hostPath:
    path: /datasets
    type: DirectoryOrCreate