apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-model
spec:
  entrypoint: build-dag
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: pvc-data
  - name: datasets
    persistentVolumeClaim:
      claimName: pvc-datasets
  arguments:
    parameters:
    - name: model
      value: LR
  templates:
  - name: build-model
    inputs: 
      parameters: 
      - name: model
    container:
      image: toddchaney/motion_prediction_build_model
      command: [python]
      args: ["run.py", "{{inputs.parameters.model}}"]
      volumeMounts:
      - mountPath: /data
        name: workspace
      - mountPath: /datasets
        name: datasets
  - name: build-dag
    dag:
      tasks:
      - name: build-model
        template: build-model
        arguments:
          parameters: 
          - name: model
            value: "{{workflow.parameters.model}}"