apiVersion: argoproject.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: clone-repo
spec:
  entrypoint: clone
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: pvc-data
  - name: datasets
    persistentVolumeClaim:
      claimName: pvc-dataset
  arguments:
    parameters:
    - name: email
      value: email@example.com
    - name: user
      value: john
  templates:
  - name: clone-repo
    inputs:
      parameters: [{name: email}, {name: user}]
    container: 
      image: toddchaney/motion_prediction_clone_repo
      env: [{name: EMAIL, value: "{{inputs.parameters.email}}"}, {name: USER, value: "{{inputs.parameters.user}}"}]
      command: [bash]
      args: ["/run.sh"]
      volumeMounts:
      - mountPath: /data
        name: workspace
      - mountPath: /datasets
        name: datasets
  - name: clone
    dag:
      tasks:
      - name: clone-repo
        template: clone-repo
        arguments: 
          parameters: [{name: email, value: "{{workflow.parameters.email}}"}, {name: user, value: "{{workflow.parameters.user}}"}]
