apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: infer
spec:
  entrypoint: infer-dag
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: pvc-data
  - name: datasets
    persistentVolumeClaim:
      claimName: pvc-dataset
  arguments:
    parameters:
    - name: model
      value: LR
  templates:
  - name: infer
    inputs:
      parameters:
      - name: model
    container: 
      image: toddchaney/motion_prediction_infer
      command: [python]
      args: ["run.py"]
      volumeMounts:
      - mountPath: /data
        name: workspace
      - mountPath: /datasets
        name: datasets
  - name: infer-dag
    dag:
      tasks:
      - name: infer-task
        template: infer
        arguments:
          parameters:
          - name: model
            value: "{{workflow.parameters.model}}"
