apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: preprocess
spec:
  entrypoint: predag
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: pvc-data
  - name: datasets
    persistentVolumeClaim:
      claimName: pvc-datasets
  templates:
  - name: preprocess
    container:
      image: toddchaney/motion_prediction_preprocess
      command: [python]
      args: ["run.py"]
      volumeMounts:
      - mountPath: /data
        name: workspace
      - mountPath: /datasets
        name: datasets
  - name: predag
    dag:
      tasks:
      - name: preprocess
        template: preprocess