apiVersion: argoproject.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: push-repo
spec:
  entrypoint: push-dag
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: pvc-data
  - name: datasets
    persistentVolumeClaim:
      claimName: pvc-dataset
  templates:
  - name: push-repo
    container: 
      image: toddchaney/motion_prediction_push_repo
      command: [bash]
      args: ["/run.sh"]
      volumeMounts:
      - mountPath: /data
        name: workspace
      - mountPath: /datasets
        name: datasets
  - name: push-dag
    dag:
      tasks:
      - name: push-repo
        template: push-repo